#!/usr/bin/env bash
#Displays to infinity and beyond indefinitely, and 'I am invincible!!'
for (( i=1; i>0; i++ ))
do
	echo "To infinity and beyond"
	     sleep 2
	     	   trap 'echo "I am invincible!!!"' SIGTERM
done
